# -*- coding: utf-8 -*-
"""Diamonds Machine Learning Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAVmYH6BZd9wjYAbixWW1WswZNVVu2GV
"""

import pandas as pd
import numpy as np
import seaborn as sns
sns.get_dataset_names()
diamonds_df = sns.load_dataset("diamonds")
diamonds_df.head()

X = diamonds_df.drop(["price"], axis=1)
Y = diamonds_df["price"]

X.head()
Y.head()

numerical = X.drop(["cut", "color", "clarity"], axis=1)
numerical.head()
categorical = X.filter(['cut', 'color', 'clarity'])
categorical.head()

cat_numerical = pd.get_dummies(categorical,drop_first=True)
cat_numerical.head()

X = pd.concat([numerical, cat_numerical], axis = 1)
X.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y,
test_size=0.20, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #scaling the training set
X_test = sc.transform(X_test) #scaling the test set

from sklearn.linear_model import LinearRegression
# training the algorithm
lin_reg = LinearRegression()
regressor = lin_reg.fit(X_train, y_train)
# making predictions on test set
y_pred = regressor.predict(X_test)

from sklearn import metrics
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=5)
regressor = knn_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

from sklearn import metrics
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(random_state=42, n_estimators=500)
regressor = rf_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

from sklearn import metrics
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

from sklearn import svm
svm_reg = svm.SVR()
regressor = svm_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

from sklearn import metrics
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

from sklearn.model_selection import cross_val_score
print(cross_val_score(regressor, X, Y, cv=5, scoring="neg_mean_absolute_error"))

from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(random_state=42, n_estimators=100)
regressor = rf_reg.fit(X_train, y_train)
single_record = sc.transform (X.values[100]. reshape(1, -1))
predicted_tip = regressor.predict(single_record)
print(predicted_tip)