# -*- coding: utf-8 -*-
"""New Linear Regression Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6dnRjkZEG5jS8F2UO2MZeLgLW2xsduJ
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/Sanchitbhadani-1/Exploring-Pandas/main/Pandas-Summative/housing.csv")

df.head()

df.describe()

df.isnull().sum()

df.dtypes

X = df.drop(["price", "prefarea", "furnishingstatus"], axis=1)
Y = df["price"]


X.head()
Y.head()

numerical = X.drop(["mainroad", "guestroom", "basement", "hotwaterheating", "airconditioning"], axis=1)
numerical.head()
categorical = X.filter(["mainroad", "guestroom", "basement", "hotwaterheating", "airconditioning"])
categorical.head()

cat_numerical = pd.get_dummies(categorical,drop_first=True)
cat_numerical.head()
X = pd.concat([numerical, cat_numerical], axis = 1)
X.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #scaling the training set
X_test = sc.transform(X_test) #scaling the test set

from sklearn.linear_model import LinearRegression
# training the algorithm
lin_reg = LinearRegression()
regressor = lin_reg.fit(X_train, y_train)
# making predictions on test set
y_pred = regressor.predict(X_test)

from sklearn import metrics
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.6)
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--'
)

plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted Prices (Linear Regression)")
plt.show()

from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=5)
regressor = knn_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(random_state=42, n_estimators=500)
regressor = rf_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

from sklearn import svm
svm_reg = svm.SVR()
regressor = svm_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

# Plot 1: Scatter plot of Area vs. Price
plt.figure(figsize=(10, 6))
sns.scatterplot(x='area', y='price', data=df)
plt.title('Area vs. Price')
plt.xlabel('Area')
plt.ylabel('Price')
plt.show()

# Plot 2: Bar plot of Price by Furnishing Status
plt.figure(figsize=(10, 6))
sns.barplot(x='furnishingstatus', y='price', data=df)
plt.title('Average Price by Furnishing Status')
plt.xlabel('Furnishing Status')
plt.ylabel('Average Price')
plt.show()